openapi: 3.0.4
info:
  title: TTRPGNoteTaker API
  description: Manages collections of notes for a user's table-top roleplaying games
  version: 0.1.0
servers:
  - url: http://localhost:3000
paths:
  /games:
    get:
      summary: List all Games
      responses:
        '200':
          description: A list of Games
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
        '5XX':
          description: Unexpected error
    post:
      summary: Add a new Game
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
      responses:
        '201':
          description: Created
        '400':
          description: Bad request, invalid Game data
        '5XX':
          description: Unexpected error 
  /games/{id}:
    get:
      summary: Get a single Game by ID
      parameters:
        - name: id
          in: path
          desciption: Game ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A Game object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '400':
          description: Bad request. Game ID must be an integer and larger than 0
        '404':
          description: Game at the specified ID was not found
        '5XX':
          description: Unexpected error
    put:
      summary: Updates an existing Game
      parameters:
        - name: id
          in: path
          desciption: Game ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
      responses:
        '200':
          description: Updated
        '400':
          description: Bad request, invalid Game data
        '404':
          description: Game at the specified ID was not found
        '5XX':
          description: Unexpected error 
    delete:
      summary: Deleted an existing Game
      parameters:
        - name: id
          in: path
          desciption: Game ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Deleted
        '400':
          description: Bad request. Game ID must be an integer and larger than 0
        '404':
          description: Game at the specified ID was not found
        '5XX':
          description: Unexpected error 
  /games/{id}/notes:
    get:
      summary: Gets all Notes for a Game
      parameters:
        - name: id
          in: path
          description: Game ID
          reqiured: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A list of Notes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
        '400':
          description: Bad request. Game ID must be an integer and larger than 0
        '404':
          description: Game at the specified ID was not found
        '5XX':
          description: Unexpected error
  /notes:
    post:
      summary: Add a new Note
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      responses:
        '201':
          description: Created
        '400':
          description: Bad request, invalid Note data
        '5XX':
          description: Unexpected error
  /notes/{noteUniqueId}:
    get:
      summary: Get a single Note by its unique ID
      parameters:
        - name: noteUniqueId
          in: path
          desciption: Note Unique ID
          required: true
          schema:
            type: string
            format: int64
      responses:
        '200':
          description: A Note object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '404':
          description: Note at the specified ID was not found
        '5XX':
          description: Unexpected error
    put:
      summary: Updates an existing Note
      parameters:
        - name: noteUniqueId
          in: path
          desciption: Note Unique ID
          required: true
          schema:
            type: string
            format: int64 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      responses:
        '200':
          description: Updated
        '400':
          description: Bad request, invalid Note data
        '404':
          description: Note at the specified ID was not found
        '5XX':
          description: Unexpected error 
    delete:
      summary: Deleted an existing Note
      parameters:
        - name: noteUniqueId
          in: path
          desciption: Note Unique ID
          required: true
          schema:
            type: string
            format: int64
      responses:
        '200':
          description: Deleted
        '400':
          description: Bad request. Note ID must be an integer and larger than 0
        '404':
          description: Note at the specified ID was not found
        '5XX':
          description: Unexpected error 
components:
  schemas:
    Game:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        notes:
          type: Note[]
    Note:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        noteUniqueId:
          type: string
        type:
          type: string
        body:
          type: string
        tags:
          type: string[]