openapi: 3.0.4
info:
  title: TTRPGNoteTaker API
  description: Manages collections of notes for a user's table-top roleplaying games
  version: 0.0.1
servers:
  - url: http://localhost:3000
paths:
  /ping:
    get:
      summary: Test route
      responses:
        '200':
          description: Will respond 'ping'
  /games:
    get:
      summary: List all games
      responses:
        '200':
          description: A list of games
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
        '5XX':
          description: Unexpected error
  /games/{id}:
    get:
      summary: Get a single game by ID
      parameters:
        - name: id
          in: path
          desciption: Game ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A Game object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '400':
          description: Bad request. Game ID must be an integer and larger than 0
        '404':
          description: Game at the specified ID was not found
        '5XX':
          description: Unexpected error
components:
  schemas:
    Game:
      type: Object
      properties:
        id:
          type: integer
        name:
          type: string
        notes:
          type: Note[]
    Note:
      type: Object
      properties:
        id:
          type: integer
        title:
          type: string
        type:
          type: string
        body:
          type: string
        tags:
          type: string[]